# Let's polish my numpy skills with w3schools
as i already know numpy but need more confidence in it, i will kind of revising it via w3schools in a more structured manner.

## Creating an array
to creatte an array, we can pass a list, tuple or any array-like object into np.array() method

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) #list
arr2 = np.array((1, 2, 3, 4, 5)) #tuple

print(arr, arr2)

print(type(arr), type(arr2))

[1 2 3 4 5] [1 2 3 4 5]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


### Dimensions in arrays
#### 0-D or scalars

In [5]:
arr0D = np.array(42)
print(arr0D)

42


#### 1-D

In [7]:
arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D)

[1 2 3 4 5]


#### 2-D

In [ ]:
arr2D = np.array([[1,2,3], [4, 5,6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


#### 3-D

In [26]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 3], [44, 55, 66]]])
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22  3]
  [44 55 66]]]


#### check number of dimensions

In [14]:
print(arr3D.ndim)
callable(arr3D.ndim) # this is how you know if a function is callable or not

3


False

#### Higher dimensional Arrays
we can define number of dimensions while creating an array

In [17]:
arrHD = np.array([1, 2, 3, 4], ndmin=5)
print(arrHD)
print('number of dim :', arrHD.ndim)

[[[[[1 2 3 4]]]]]
number of dim : 5


in this array the innermost dim(5th dim) has 4 elements, 4th dim has 1, 3rd has 1, 2nd has 1 too and so had 1st

## Numpy array indexing
### Access array elements
array indexing is same as accessing an array element

In [20]:
# arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
print(arr[4])

1
2
5


#### Accessing 2-D
we can use comma seperated integers representing dimension and the index of the element.  
think of dimension like row and index as column for the array 

In [ ]:
# arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print('2nd element of 1st row: ', arr2D[0, 1])

2nd element of 1st row:  2


#### Accessing 3-D
we can use comma seperated integers representing the dimensions and the index of the element

In [27]:
# arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 3], [44, 55, 66]]])
print(arr3D[0, 1, 2])

6


#### Negative indexing
we can use negative indexing to access an array from end

In [29]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print('last element from 2nd dim: ', array1[1, -1])

last element from 2nd dim:  6


## Numpy array slicing
### Slicing arrays
slicing here means making an array by taking element from one element to another.  
* we pass slice instead of index like this: *[start:end]*  
* we can also define the step, like this: *[start:end:step]*  
* if we don't pass start, it's considered 0  
* if we don't pass end, it's condidered length of array in that dimension  
* if we don't pass step, its considered 1  
**The result includes the start index but exludes the end index**

In [30]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7])
print(array2[1:5])

[2 3 4 5]


#### Negative slicing
use the minus operator to refer an index from the end

In [31]:
print(array2[-3:-1])

[5 6]


#### Step
we use **step** to have steps in our slicing

In [33]:
print(array2[1:5:2])

[2 4]


returning every alternate element

In [34]:
print(array2[::2])

[1 3 5 7]


### Slicing 2-D arrays

In [35]:
# from the second element, slice elements from index 1 to index 4 (not included)

arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr2[1, 1:4])

[7 8 9]


we can also use slicing for both dim and index

In [38]:
qrr = np.array([10, 15, 20, 25, 30, 35, 40])
print(qrr[1:4:2])

[15 25]


[yaha se](https://www.w3schools.com/python/numpy/numpy_data_types.asp)