# Let's polish my numpy skills with w3schools
as i already know numpy but need more confidence in it, i will kind of revising it via w3schools in a more structured manner.

## Creating an array
to creatte an array, we can pass a list, tuple or any array-like object into np.array() method

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) #list
arr2 = np.array((1, 2, 3, 4, 5)) #tuple

print(arr, arr2)

print(type(arr), type(arr2))

[1 2 3 4 5] [1 2 3 4 5]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


### Dimensions in arrays
#### 0-D or scalars

In [3]:
arr0D = np.array(42)
print(arr0D)

42


#### 1-D

In [4]:
arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D)

[1 2 3 4 5]


#### 2-D

In [5]:
arr2D = np.array([[1,2,3], [4, 5,6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


#### 3-D

In [6]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 3], [44, 55, 66]]])
print(arr3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22  3]
  [44 55 66]]]


#### check number of dimensions

In [7]:
print(arr3D.ndim)
callable(arr3D.ndim) # this is how you know if a function is callable or not

3


False

#### Higher dimensional Arrays
we can define number of dimensions while creating an array

In [8]:
arrHD = np.array([1, 2, 3, 4], ndmin=5)
print(arrHD)
print('number of dim :', arrHD.ndim)

[[[[[1 2 3 4]]]]]
number of dim : 5


in this array the innermost dim(5th dim) has 4 elements, 4th dim has 1, 3rd has 1, 2nd has 1 too and so had 1st

## Numpy array indexing
### Access array elements
array indexing is same as accessing an array element

In [9]:
# arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1])
print(arr[4])

1
2
5


#### Accessing 2-D
we can use comma seperated integers representing dimension and the index of the element.  
think of dimension like row and index as column for the array 

In [10]:
# arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print('2nd element of 1st row: ', arr2D[0, 1])

2nd element of 1st row:  2


#### Accessing 3-D
we can use comma seperated integers representing the dimensions and the index of the element

In [11]:
# arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 22, 3], [44, 55, 66]]])
print(arr3D[0, 1, 2])

6


#### Negative indexing
we can use negative indexing to access an array from end

In [12]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])

print('last element from 2nd dim: ', array1[1, -1])

last element from 2nd dim:  6


## Numpy array slicing
### Slicing arrays
slicing here means making an array by taking element from one element to another.  
* we pass slice instead of index like this: *[start:end]*  
* we can also define the step, like this: *[start:end:step]*  
* if we don't pass start, it's considered 0  
* if we don't pass end, it's condidered length of array in that dimension  
* if we don't pass step, its considered 1  
**The result includes the start index but exludes the end index**

In [13]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7])
print(array2[1:5])

[2 3 4 5]


#### Negative slicing
use the minus operator to refer an index from the end

In [14]:
print(array2[-3:-1])

[5 6]


#### Step
we use **step** to have steps in our slicing

In [15]:
print(array2[1:5:2])

[2 4]


returning every alternate element

In [16]:
print(array2[::2])

[1 3 5 7]


### Slicing 2-D arrays

In [17]:
# from the second element, slice elements from index 1 to index 4 (not included)

arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr2[1, 1:4])

[7 8 9]


we can also use slicing for both dim and index

In [18]:
qrr = np.array([10, 15, 20, 25, 30, 35, 40])
print(qrr[1:4:2])

[15 25]


## Data types in numpy

getting the datatype of a numpy array

In [19]:
print(arr.dtype)
strArr  = np.array(['ssssh', 'as', 'hi'])
print(strArr.dtype)

int32
<U5


here's a list of codes for each datatype in numpy  
* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string (the number that follows it shows the length of longest string)
* V - fixed chunk of memory for other type ( void )

### Creating an array with specified datatype
in numpy we can specify the data type of elements while creating an array

In [20]:
arrString = np.array([1, 2, 3, 4], dtype='S')
print(arrString)

[b'1' b'2' b'3' b'4']


For i, u, f, S and U we can define size as well.  
for example we can create an array of datatype i4, which means number which takes 4 bytes (i.e., 32 bits) size

In [21]:
arr4bit = np.array([4, 5, 6], dtype='i4')
print(arr4bit.dtype)

int32


### Converting datatype of an existing array
one way to convert the datatype of a numpy array is to create a copy of it using astype() function which gives us the ability to specify the datatype as an argument.  
for example

In [22]:
arrInt = arrString.astype(dtype='i')
print(arrInt)
print(arrInt.dtype)

[1 2 3 4]
int32


we can also convert from int to boolean

In [23]:
arrBool = np.array([1, 0, 3]).astype(dtype=bool)
print(arrBool)

[ True False  True]


## Numpy array COPY vs VIEW
the main difference between both is that the copy is a new array independent of the original one while view is just a view of the original one, so any change to copy won't affect the original one but for view it does.  
### COPY
for example copying an array and then making changes to the copy

In [24]:
arrOrig = np.array([2, 4, 7])
arrCopy = arrOrig.copy()
arrCopy[0] = 9

print(arrOrig)
print(arrCopy)

[2 4 7]
[9 4 7]


### VIEW
for example, create a view and then edit the original one and then print both

In [25]:
arrView = arrOrig.view()
arrOrig[0] = 12

print(arrOrig)
print(arrView)

[12  4  7]
[12  4  7]


so it's a view, that's why both changed.  
now let's make a change in the view and then see both

In [26]:
arrView[1] = 98

print(arrView)
print(arrOrig)

[12 98  7]
[12 98  7]


again both changes, as stated earlier.  
### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?  
Every NumPy array has the attribute base that returns None if the array owns the data.  
Otherwise, the base  attribute refers to the original object.  

In [27]:
print(arrView.base)
print(arrCopy.base)
print(arrOrig.base)

[12 98  7]
None
None


## Numpy array shape
shape of an array is the number of elements in each dimension.  
shape() returns a tuple of sizes

In [28]:
print(arr2D.shape)

(2, 3)


The example above returns (2, 3), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 3.  
  
creating an array with shape 5 using **ndmin**

In [29]:
arr5 = np.array([1, 2, 3, 4], ndmin=5)

print(arr5)
print(arr5.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## Array reshaping
we can reshape an array into different other shapes.  

In [30]:
newArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

reshapedArr = newArr.reshape((2, 5))

reshapedArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

we can reshape to any shape as long as number of elements is possible for that shape.  
for example we cannot reshape a vector of length 10 into an array of (3, 3) shape, because this shape can only have **9** elements while there are 10.  
**Note: this reshaped array is a view of the original array and not the copy**

### Unknown shape
we can also pass **-1** in shape and numpy will calculate that number for you.  
for example:

In [31]:
reshapedArr2 = newArr.reshape((2, -1))
reshapedArr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Flatening the array
we can change an array of any shape into a 1-D array.  
we pass -1 as shape to do so

In [32]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
newarr

array([1, 2, 3, 4, 5])

## Numpy array iterating
we can iterate over elements of an array using for loop (like a list)

In [33]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


iterating 2D array

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


iterating over each element of the array

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


### iterating arrays using nditer
if we use basic **for** loop then in order to iterate over each element we would need n **for** loops which can be computationaly expensive as well as messy, so to solve that numpy has **nditer**.

In [36]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### Iterating with different step size
we can also iterate over an array with a step size, by passing not the whole array but a **slice** of it which is sliced with step size to the **nditer()**

In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


### Enumerated Iteration Using ndenumerate()
sometimes we need the index of element too while iterating. That's when we use eumeration which returns element as well as it's index while iterating. (index, element).

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])

for i, x in np.ndenumerate(arr):
    print(i, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


now let's try on a 2D array

In [39]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for i, x in np.ndenumerate(arr):
    print(i, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## Joining arrays
in numpy we can add two or more numpy arrays into one by using concatenate()...  
the arrays are added by axis, we can specify or it is by default as 0.

In [43]:
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 4, 6])

arrF = np.concatenate((arr1, arr2))
arrF

array([1, 3, 5, 2, 4, 6])

now joining 2D arrays

In [47]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr11 = np.concatenate((arr1, arr2), axis=1)
arr0 = np.concatenate((arr1, arr2), axis=0)

print(arr11)
print(arr0)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Joining arrays using stacking
stacking is same as concatenating, the only difference is stacking creates new axis.  

* concatenate → same dimensionality, extend an axis.
* stack → increase dimensionality by 1, new axis appears.

In [54]:
arrStacked = np.stack((arr1, arr2), axis=1)
print(arrStacked.shape)
print(arrStacked)

(2, 2, 2)
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


### Stacking along rows
numpy have **hstack** to stack along row

In [51]:
arrRS = np.hstack((arr1, arr2))
print(arrRS)
print(arrRS.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


similarly we have  
### Stacking along columns
nump have **vstack** for this too

In [55]:
arrVS = np.vstack((arr1, arr2))
print(arrVS)
print(arrVS.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


### Stacking Along Height (depth)
numpy have dstack to stack along height (which is depth too)

In [56]:
arrDS = np.dstack((arr1, arr2))
print(arrDS)
print(arrDS.shape)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


[yaha se](https://www.w3schools.com/python/numpy/numpy_array_split.asp)